apiVersion: v1
kind: Secret
metadata:
  # * NOMBRE DE ARCHIVO RELEVANTE PARA ACCEDER A LOS KEY-VALUES
  name: pgadmin-secrets
type: Opaque
data:
  # alan@gmail.com
  PG_USER_EMAIL: YWxhbkBnbWFpbC5jb20=
  # 5545896216Alan150402+$
  DB_PASSWORD: NTU0NTg5NjIxNkFsYW4xNTA0MDIrJA==