apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config # * NOMBRE DE ARCHIVO RELEVANTE PARA ACCEDER A LOS KEY-VALUES
data:
  # * AQUI SE ENCUENTRAN LOS KEY VALUES
  DB_NAME: postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"
  
