apiVersion: v1
kind: Secret
metadata:
  # * NOMBRE DE ARCHIVO RELEVANTE PARA ACCEDER A LOS KEY-VALUES
  name: postgres-secrets
type: Opaque
data:
  # postgres
  DB_USERNAME: cG9zdGdyZXM=
  # 5545896216Alan150402+$
  DB_PASSWORD: NTU0NTg5NjIxNkFsYW4xNTA0MDIrJA==